// Phy_inst_rx_is_lockedtodata_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_is_lockedtodata_bfm_ip (
		input  wire [0:0] sig_rx_is_lockedtodata  // conduit.rx_is_lockedtodata
	);

	Phy_inst_rx_is_lockedtodata_bfm_ip_altera_conduit_bfm_171_hqmdh2y phy_inst_rx_is_lockedtodata_bfm (
		.sig_rx_is_lockedtodata (sig_rx_is_lockedtodata)  //   input,  width = 1, conduit.rx_is_lockedtodata
	);

endmodule
