// Phy_inst_rx_enh_highber_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_enh_highber_bfm_ip (
		input  wire [0:0] sig_rx_enh_highber  // conduit.rx_enh_highber
	);

	Phy_inst_rx_enh_highber_bfm_ip_altera_conduit_bfm_171_yxtgjaq phy_inst_rx_enh_highber_bfm (
		.sig_rx_enh_highber (sig_rx_enh_highber)  //   input,  width = 1, conduit.rx_enh_highber
	);

endmodule
