// Phy_inst_tx_control_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_control_bfm_ip (
		output wire [7:0] sig_tx_control  // conduit.tx_control
	);

	Phy_inst_tx_control_bfm_ip_altera_conduit_bfm_171_od2ecna phy_inst_tx_control_bfm (
		.sig_tx_control (sig_tx_control)  //  output,  width = 8, conduit.tx_control
	);

endmodule
