// Phy_inst_unused_rx_control_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_unused_rx_control_bfm_ip (
		input  wire [11:0] sig_unused_rx_control  // conduit.unused_rx_control
	);

	Phy_inst_unused_rx_control_bfm_ip_altera_conduit_bfm_171_a6vkyjy phy_inst_unused_rx_control_bfm (
		.sig_unused_rx_control (sig_unused_rx_control)  //   input,  width = 12, conduit.unused_rx_control
	);

endmodule
