// Phy_inst_rx_analogreset_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_analogreset_bfm_ip (
		output wire [0:0] sig_rx_analogreset  // conduit.rx_analogreset
	);

	Phy_inst_rx_analogreset_bfm_ip_altera_conduit_bfm_171_suzcfci phy_inst_rx_analogreset_bfm (
		.sig_rx_analogreset (sig_rx_analogreset)  //  output,  width = 1, conduit.rx_analogreset
	);

endmodule
