// Phy_inst_tx_enh_fifo_empty_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_enh_fifo_empty_bfm_ip (
		input  wire [0:0] sig_tx_enh_fifo_empty  // conduit.tx_enh_fifo_empty
	);

	Phy_inst_tx_enh_fifo_empty_bfm_ip_altera_conduit_bfm_171_rpvn5oi phy_inst_tx_enh_fifo_empty_bfm (
		.sig_tx_enh_fifo_empty (sig_tx_enh_fifo_empty)  //   input,  width = 1, conduit.tx_enh_fifo_empty
	);

endmodule
