// Phy_inst_tx_cal_busy_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_cal_busy_bfm_ip (
		input  wire [0:0] sig_tx_cal_busy  // conduit.tx_cal_busy
	);

	Phy_inst_tx_cal_busy_bfm_ip_altera_conduit_bfm_171_s7zyary phy_inst_tx_cal_busy_bfm (
		.sig_tx_cal_busy (sig_tx_cal_busy)  //   input,  width = 1, conduit.tx_cal_busy
	);

endmodule
