// Phy_inst_rx_parallel_data_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_parallel_data_bfm_ip (
		input  wire [63:0] sig_rx_parallel_data  // conduit.rx_parallel_data
	);

	Phy_inst_rx_parallel_data_bfm_ip_altera_conduit_bfm_171_2fwttky phy_inst_rx_parallel_data_bfm (
		.sig_rx_parallel_data (sig_rx_parallel_data)  //   input,  width = 64, conduit.rx_parallel_data
	);

endmodule
