// Phy_inst_tx_digitalreset_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_digitalreset_bfm_ip (
		output wire [0:0] sig_tx_digitalreset  // conduit.tx_digitalreset
	);

	Phy_inst_tx_digitalreset_bfm_ip_altera_conduit_bfm_171_kpoqata phy_inst_tx_digitalreset_bfm (
		.sig_tx_digitalreset (sig_tx_digitalreset)  //  output,  width = 1, conduit.tx_digitalreset
	);

endmodule
