// Phy_inst_rx_serial_data_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_serial_data_bfm_ip (
		output wire [0:0] sig_rx_serial_data  // conduit.rx_serial_data
	);

	Phy_inst_rx_serial_data_bfm_ip_altera_conduit_bfm_171_xh3a7uq phy_inst_rx_serial_data_bfm (
		.sig_rx_serial_data (sig_rx_serial_data)  //  output,  width = 1, conduit.rx_serial_data
	);

endmodule
