// Phy_inst_unused_tx_parallel_data_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_unused_tx_parallel_data_bfm_ip (
		output wire [63:0] sig_unused_tx_parallel_data  // conduit.unused_tx_parallel_data
	);

	Phy_inst_unused_tx_parallel_data_bfm_ip_altera_conduit_bfm_171_pvaewry phy_inst_unused_tx_parallel_data_bfm (
		.sig_unused_tx_parallel_data (sig_unused_tx_parallel_data)  //  output,  width = 64, conduit.unused_tx_parallel_data
	);

endmodule
