// Phy_inst_reconfig_avmm_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_reconfig_avmm_bfm_ip (
		output wire [9:0]  sig_address,     // conduit.address
		output wire [0:0]  sig_read,        //        .read
		input  wire [31:0] sig_readdata,    //        .readdata
		input  wire [0:0]  sig_waitrequest, //        .waitrequest
		output wire [0:0]  sig_write,       //        .write
		output wire [31:0] sig_writedata    //        .writedata
	);

	Phy_inst_reconfig_avmm_bfm_ip_altera_conduit_bfm_171_k2a7pti phy_inst_reconfig_avmm_bfm (
		.sig_address     (sig_address),     //  output,  width = 10, conduit.address
		.sig_read        (sig_read),        //  output,   width = 1,        .read
		.sig_readdata    (sig_readdata),    //   input,  width = 32,        .readdata
		.sig_waitrequest (sig_waitrequest), //   input,   width = 1,        .waitrequest
		.sig_write       (sig_write),       //  output,   width = 1,        .write
		.sig_writedata   (sig_writedata)    //  output,  width = 32,        .writedata
	);

endmodule
