// Phy_inst_rx_cal_busy_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_cal_busy_bfm_ip (
		input  wire [0:0] sig_rx_cal_busy  // conduit.rx_cal_busy
	);

	Phy_inst_rx_cal_busy_bfm_ip_altera_conduit_bfm_171_3ukswuy phy_inst_rx_cal_busy_bfm (
		.sig_rx_cal_busy (sig_rx_cal_busy)  //   input,  width = 1, conduit.rx_cal_busy
	);

endmodule
