#!/usr/bin/perl
# Copyright (C) 1998-2000 Raydiant
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public LIcense
# as published by the Free Software Foundation;  either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABLILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

$Program = $0;
# ==================================================
# LOCATE THE INI, execute it to get the stuff needed
# Also call the first verion of $Program found
# ==================================================

($VHome = $0) =~ s/([^\/]*)$//;
$VHome = "." if ( $VHome eq "" );

require "${VHome}/fileutils.pl";

&LaunchPerl($Program, @ARGV);

