// XG_inst_xgmii_rx_control_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module XG_inst_xgmii_rx_control_bfm_ip (
		output wire [3:0] sig_export  // conduit.export
	);

	XG_inst_xgmii_rx_control_bfm_ip_altera_conduit_bfm_171_pnd4avi xg_inst_xgmii_rx_control_bfm (
		.sig_export (sig_export)  //  output,  width = 4, conduit.export
	);

endmodule
