// Phy_inst_tx_err_ins_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_err_ins_bfm_ip (
		output wire [0:0] sig_tx_err_ins  // conduit.tx_err_ins
	);

	Phy_inst_tx_err_ins_bfm_ip_altera_conduit_bfm_171_b5kmjbi phy_inst_tx_err_ins_bfm (
		.sig_tx_err_ins (sig_tx_err_ins)  //  output,  width = 1, conduit.tx_err_ins
	);

endmodule
