// Phy_inst_rx_is_lockedtoref_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_is_lockedtoref_bfm_ip (
		input  wire [0:0] sig_rx_is_lockedtoref  // conduit.rx_is_lockedtoref
	);

	Phy_inst_rx_is_lockedtoref_bfm_ip_altera_conduit_bfm_171_cht2buy phy_inst_rx_is_lockedtoref_bfm (
		.sig_rx_is_lockedtoref (sig_rx_is_lockedtoref)  //   input,  width = 1, conduit.rx_is_lockedtoref
	);

endmodule
