// Phy_inst_tx_parallel_data_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_parallel_data_bfm_ip (
		output wire [63:0] sig_tx_parallel_data  // conduit.tx_parallel_data
	);

	Phy_inst_tx_parallel_data_bfm_ip_altera_conduit_bfm_171_krd3h5a phy_inst_tx_parallel_data_bfm (
		.sig_tx_parallel_data (sig_tx_parallel_data)  //  output,  width = 64, conduit.tx_parallel_data
	);

endmodule
