// Phy_inst_rx_enh_data_valid_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_enh_data_valid_bfm_ip (
		input  wire [0:0] sig_rx_enh_data_valid  // conduit.rx_enh_data_valid
	);

	Phy_inst_rx_enh_data_valid_bfm_ip_altera_conduit_bfm_171_cp6emyy phy_inst_rx_enh_data_valid_bfm (
		.sig_rx_enh_data_valid (sig_rx_enh_data_valid)  //   input,  width = 1, conduit.rx_enh_data_valid
	);

endmodule
