// Phy_inst_tx_enh_data_valid_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_enh_data_valid_bfm_ip (
		output wire [0:0] sig_tx_enh_data_valid  // conduit.tx_enh_data_valid
	);

	Phy_inst_tx_enh_data_valid_bfm_ip_altera_conduit_bfm_171_ku5zdby phy_inst_tx_enh_data_valid_bfm (
		.sig_tx_enh_data_valid (sig_tx_enh_data_valid)  //  output,  width = 1, conduit.tx_enh_data_valid
	);

endmodule
