// XG_inst_avalon_st_rxstatus_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module XG_inst_avalon_st_rxstatus_bfm_ip #(
		parameter USE_PACKET       = 0,
		parameter USE_CHANNEL      = 0,
		parameter USE_ERROR        = 1,
		parameter USE_READY        = 0,
		parameter USE_VALID        = 1,
		parameter USE_EMPTY        = 0,
		parameter ST_SYMBOL_W      = 8,
		parameter ST_NUMSYMBOLS    = 5,
		parameter ST_CHANNEL_W     = 1,
		parameter ST_ERROR_W       = 7,
		parameter ST_EMPTY_W       = 3,
		parameter ST_READY_LATENCY = 0,
		parameter ST_BEATSPERCYCLE = 1,
		parameter ST_MAX_CHANNELS  = 0,
		parameter VHDL_ID          = 1
	) (
		input  wire        clk,        //       clk.clk
		input  wire        reset,      // clk_reset.reset
		input  wire [39:0] sink_data,  //      sink.data
		input  wire [0:0]  sink_valid, //          .valid
		input  wire [6:0]  sink_error  //          .error
	);

	altera_avalon_st_sink_bfm #(
		.USE_PACKET       (USE_PACKET),
		.USE_CHANNEL      (USE_CHANNEL),
		.USE_ERROR        (USE_ERROR),
		.USE_READY        (USE_READY),
		.USE_VALID        (USE_VALID),
		.USE_EMPTY        (USE_EMPTY),
		.ST_SYMBOL_W      (ST_SYMBOL_W),
		.ST_NUMSYMBOLS    (ST_NUMSYMBOLS),
		.ST_CHANNEL_W     (ST_CHANNEL_W),
		.ST_ERROR_W       (ST_ERROR_W),
		.ST_EMPTY_W       (ST_EMPTY_W),
		.ST_READY_LATENCY (ST_READY_LATENCY),
		.ST_BEATSPERCYCLE (ST_BEATSPERCYCLE),
		.ST_MAX_CHANNELS  (ST_MAX_CHANNELS),
		.VHDL_ID          (VHDL_ID)
	) xg_inst_avalon_st_rxstatus_bfm (
		.clk                (clk),        //   input,   width = 1,       clk.clk
		.reset              (reset),      //   input,   width = 1, clk_reset.reset
		.sink_data          (sink_data),  //   input,  width = 40,      sink.data
		.sink_valid         (sink_valid), //   input,   width = 1,          .valid
		.sink_error         (sink_error), //   input,   width = 7,          .error
		.sink_ready         (),           // (terminated),                        
		.sink_startofpacket (1'b0),       // (terminated),                        
		.sink_endofpacket   (1'b0),       // (terminated),                        
		.sink_empty         (3'b000),     // (terminated),                        
		.sink_channel       (1'b0)        // (terminated),                        
	);

endmodule
