// Phy_inst_tx_serial_clk0_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_serial_clk0_bfm_ip (
		output wire [0:0] sig_clk  // conduit.clk
	);

	Phy_inst_tx_serial_clk0_bfm_ip_altera_conduit_bfm_171_sfxe7bq phy_inst_tx_serial_clk0_bfm (
		.sig_clk (sig_clk)  //  output,  width = 1, conduit.clk
	);

endmodule
