// Phy_inst_rx_clkout_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_clkout_bfm_ip (
		input  wire [0:0] sig_clk  // conduit.clk
	);

	Phy_inst_rx_clkout_bfm_ip_altera_conduit_bfm_171_dvp26vy phy_inst_rx_clkout_bfm (
		.sig_clk (sig_clk)  //   input,  width = 1, conduit.clk
	);

endmodule
