// XG_inst_xgmii_tx_control_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module XG_inst_xgmii_tx_control_bfm_ip (
		input  wire [3:0] sig_export  // conduit.export
	);

	XG_inst_xgmii_tx_control_bfm_ip_altera_conduit_bfm_171_iyxfdgi xg_inst_xgmii_tx_control_bfm (
		.sig_export (sig_export)  //   input,  width = 4, conduit.export
	);

endmodule
