// Phy_inst_rx_enh_fifo_del_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_enh_fifo_del_bfm_ip (
		input  wire [0:0] sig_rx_enh_fifo_del  // conduit.rx_enh_fifo_del
	);

	Phy_inst_rx_enh_fifo_del_bfm_ip_altera_conduit_bfm_171_oi4ohtq phy_inst_rx_enh_fifo_del_bfm (
		.sig_rx_enh_fifo_del (sig_rx_enh_fifo_del)  //   input,  width = 1, conduit.rx_enh_fifo_del
	);

endmodule
