// Phy_inst_unused_tx_control_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_unused_tx_control_bfm_ip (
		output wire [8:0] sig_unused_tx_control  // conduit.unused_tx_control
	);

	Phy_inst_unused_tx_control_bfm_ip_altera_conduit_bfm_171_fgfakmq phy_inst_unused_tx_control_bfm (
		.sig_unused_tx_control (sig_unused_tx_control)  //  output,  width = 9, conduit.unused_tx_control
	);

endmodule
