// Phy_inst_tx_enh_fifo_full_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_enh_fifo_full_bfm_ip (
		input  wire [0:0] sig_tx_enh_fifo_full  // conduit.tx_enh_fifo_full
	);

	Phy_inst_tx_enh_fifo_full_bfm_ip_altera_conduit_bfm_171_bkhzbdi phy_inst_tx_enh_fifo_full_bfm (
		.sig_tx_enh_fifo_full (sig_tx_enh_fifo_full)  //   input,  width = 1, conduit.tx_enh_fifo_full
	);

endmodule
