// Phy_inst_rx_enh_fifo_insert_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_enh_fifo_insert_bfm_ip (
		input  wire [0:0] sig_rx_enh_fifo_insert  // conduit.rx_enh_fifo_insert
	);

	Phy_inst_rx_enh_fifo_insert_bfm_ip_altera_conduit_bfm_171_te4nuui phy_inst_rx_enh_fifo_insert_bfm (
		.sig_rx_enh_fifo_insert (sig_rx_enh_fifo_insert)  //   input,  width = 1, conduit.rx_enh_fifo_insert
	);

endmodule
