// Phy_inst_tx_serial_data_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_tx_serial_data_bfm_ip (
		input  wire [0:0] sig_tx_serial_data  // conduit.tx_serial_data
	);

	Phy_inst_tx_serial_data_bfm_ip_altera_conduit_bfm_171_ydb2hoq phy_inst_tx_serial_data_bfm (
		.sig_tx_serial_data (sig_tx_serial_data)  //   input,  width = 1, conduit.tx_serial_data
	);

endmodule
