// Phy_inst_rx_digitalreset_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_digitalreset_bfm_ip (
		output wire [0:0] sig_rx_digitalreset  // conduit.rx_digitalreset
	);

	Phy_inst_rx_digitalreset_bfm_ip_altera_conduit_bfm_171_jemqyza phy_inst_rx_digitalreset_bfm (
		.sig_rx_digitalreset (sig_rx_digitalreset)  //  output,  width = 1, conduit.rx_digitalreset
	);

endmodule
