// Phy_inst_reconfig_reset_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_reconfig_reset_bfm_ip (
		output wire [0:0] sig_reset  // conduit.reset
	);

	Phy_inst_reconfig_reset_bfm_ip_altera_conduit_bfm_171_tzm3ryi phy_inst_reconfig_reset_bfm (
		.sig_reset (sig_reset)  //  output,  width = 1, conduit.reset
	);

endmodule
