// XG_inst_rx_156_25_clk_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module XG_inst_rx_156_25_clk_bfm_ip #(
		parameter CLOCK_RATE = 50000000,
		parameter CLOCK_UNIT = 1
	) (
		output wire  clk  // clk.clk
	);

	altera_avalon_clock_source #(
		.CLOCK_RATE (CLOCK_RATE),
		.CLOCK_UNIT (CLOCK_UNIT)
	) xg_inst_rx_156_25_clk_bfm (
		.clk (clk)  //  output,  width = 1, clk.clk
	);

endmodule
