// Phy_inst_rx_control_bfm_ip.v

// Generated using ACDS version 17.1.2 304

`timescale 1 ps / 1 ps
module Phy_inst_rx_control_bfm_ip (
		input  wire [7:0] sig_rx_control  // conduit.rx_control
	);

	Phy_inst_rx_control_bfm_ip_altera_conduit_bfm_171_zi5pipy phy_inst_rx_control_bfm (
		.sig_rx_control (sig_rx_control)  //   input,  width = 8, conduit.rx_control
	);

endmodule
