// (C) 2001-2018 Intel Corporation. All rights reserved.
// This simulation model contains highly confidential and
// proprietary information of Intel and is being provided
// in accordance with and subject to the protections of the
// applicable Intel Program License Subscription Agreement
// which governs its use and disclosure. Your use of Intel
// Corporation's design tools, logic functions and other
// software and tools, and its AMPP partner logic functions,
// and any output files from any of the foregoing (including device
// programming or simulation files), and any associated
// documentation or information are expressly subject to the
// terms and conditions of the Intel Program License Subscription
// Agreement, Intel FPGA IP License Agreement, or other
// applicable license agreement, including, without limitation,
// that your use is for the sole purpose of simulating designs
// for use exclusively in logic devices manufactured by Intel and sold
// by Intel or its authorized distributors. Please refer to the
// applicable agreement for further details. Intel products and
// services are protected under numerous U.S. and foreign patents,
// maskwork rights, copyrights and other intellectual property laws.
// Intel assumes no responsibility or liability arising out of the
// application or use of this simulation model.
// ACDS 17.1
//pragma protect begin_protected
//pragma protect key_keyowner=Cadence Design Systems.
//pragma protect key_keyname=CDS_KEY
//pragma protect key_method=RC5
//pragma protect key_block
+hLStiPtiQ6DOJQWLXO8C8nfTEyYwjXf9nLLcl0UxAuB1mYNgXk3MUCf7wREuKZn
kMkuXkw5GkG6A52bEFmFy+IKZEmVuBUYIFzltdHVCj+ra1b1JYIZXXw6tDvOQ2G+
Jae3dIxLbPhP3uHqnhJtbDwTk3YKaJmejSeitt9Oi/+R+1bhD2Fdqw==
//pragma protect end_key_block
//pragma protect digest_block
cy4nO1cnAAD56z2WvEfldpLGdy0=
//pragma protect end_digest_block
//pragma protect data_block
R/MU2daLBPgxFEDbvKb3ElmupljbqZtEb4f+nsbcL/QFBdZMbsL96tPCAf73eTrQ
pMGsDkvln9pKuqXBxn2NR1PIiFovNr+YvtOZW9xIJzurGev2UyHYO/QQ8ilzCbFG
8Hb7Vbe6OuTu01U0Ja1HmWqABZKGfvhqFvglVrbT128risXhDEmH63RnrUX+V/6W
q7pxHMewJ/Jk8AXIzLj21ynT/4X3j+x7kIBDgwWeZUi7wE3H6oPANUCRlkOL6JDG
PdlIfmZg66IAZ04KuFB2VxtwntC2SQKyGdqjtlN/VBdu8XvNcu4fsqzathAG3Hwj
K6FWVQ2qSx05nzKuSIOMi+J1eksaF8ZCUowEZGTVtM27QguSjm740q+QyeFq830P
SXoq8IJ9u7vbizf+EwOLgY+G1h+qkAo/Kz271eHpxAVn4OZu9ZS+ZNE3riolXNLw
IlZzAe7k+jtkQTu9ZOlZc1TDLZtLoXxLji9S+mvVsIbVBvAiwzuOytx1RRmZg7C4
W+mgs2srJABfabjnl532scDnXDQwpEuQaB2RuzO14R9qoPBsGzfWrukjIReqJSDx
sy0kD3fBVUPiBVbyKHRoddLgRh1EZGH/dJAymqt/r3sSyWcdUlizBpA7Jld4Bao0
iqgxXtLyO0DwUny9P89yqzigm2pdI49ti2JzTeQzbdApSZTD6v8tbAXc3nysrHDU
tWM/mr+Mf1qIIWvSDneBReAJlZnW/mtjL4rRWKfpqArkfSoTUDVTTEUVH87EjxvG
G4i5wXhB+9m2T+hPyIVYJzMJbx7jTG7Sja4tFfZ47sNTMRnd44ETjv0aAw6V92B/
CgBSTP1oNGVOqsQYh0EQL0Z3NhEAJcDV5qRo2QkOG+u/jdhBGiDncV6b5InLqha5
KA9aeNXQFXhQmBscVBw1QT0vdQRg+q+EqCJqWSevjAlGAWkGYshC9HpKX0oBHLiC
ewtT8VjiLGGy9hTiUEGcuyAbrOaRfjwc9BPXmTZwJ3kxSDs4CkHNkh3DzFilHX4D
ddIhhdbOW2WcgTvifhBFxS0VO+3uAnfVcqZq6qD6r2JJyfD1o9j+iRPTArSiw2n7
iJGYvTAls6ODoTpn7QLoV0bENj6mgLX7qehwJkwwV6IZ9UEYZA5NtmPut47pOC+Z
htuBlM6uUZrQpsjrPfivB9K4wJ9jP+FYkN37hgNeHPaI7ZZeolSzmynEhoXUnUvw
EyfvdTj+xPsei7SZdj6K56Ov+XzI/dAbZnYZpfNyKfzCIRlg7Q86n/gjBn3qqx/E
vF+JMMr4R6P2En+pRSl0FzTSzFSx7uYrPGMLDsvwq+n/QM2HU3i5vCFE1eqKThwG
XyV0iRiSqZmvFjrhE8CoepplDlX9g1CVx/BTausNBL4d4vXuGVHGsfrGloCtmw1o
dl2iB5cKUjqrR4ibM8XvYTOljeN6Y7j4zqPFIm09lEOPX8O80WSCl7AalDjuDKCF
Tz9GlfBbkzR2zWLfl9SEq/mTJo3bLbsVmSj4UGGEzbXSK8R2Jn4H7/8BbEb8ofwg
DAOJ6gSHcvh/x0bo/ixroN1htgZUxNYu7TPS/cvcVEHmraMG/EIZ/VHDPVbYC4D+
qzwaFIZvrn7iD9/Uh9qgXhw5gx1t9/AYJwcY7SNsoZpVta9hAe9bPRK3QDnz67e6
o5Y+BBeT2tDLb4h65KEhjUYAiZ50sYMHOPRqTOcxKwEf4wCgW209Ns/VzzyE3jug
roF0Q+flNyyfchxpKvOS/2XHe+Dcu0JUvhbcIGExG1cWvS6/zB/vfaeJSG02hxGs
xbh63dfcLJlSfsyTfPOhTpvArq2aL73rvJ/j41rB/voi7B3a8hU+wpdkmwgX2nLR
I5hUbo39k4Y4ptYuttAVOh1el0yoHsm6SB0k4FMEPgNBXMxou6lpqygu7+nATOpx
RGpX0176RHsRzoSO90XvCc+9SDcfTdEmWh5wAxLeC+HYVJ3T2e8XgwjNFKwvb3QM
rA3qAszwcgBi5E7IAJeTfjsqAmC4wkl005e2ycaIP2Ea1m0RHBe1BrHo7vnd2YLM
xi3HqCRaXn/hSwX3BzhMEiCBOIJNUMt2w+yFiWupcwhbNUHpD0p1mhCeCyDxJSd3
EemugqOWsESixHke/vmu14Kt//3MLFyCL3AcyhRn0JiTko7e98WRc8v7tQs8ZtzD
e5lKK6AwFyRuLbLI1km+ckkAY9ZYuuajfCF4jj8ADbyGI1ZmmlHF4u04eoPjUa0W
oE1FyCSX6N9Y8/ihIwUheOkhW60xjM8noPgdjLbpwIyIIEdJmaAfRR5nh7HbyMbq
VpiBiqzsBJJRZkfdhQyj4vGntcXZ8c1VGpsHM8YxlwO4IRGqsufa3kSzYKj5RVLr
FwIaRp+c7/env5eXjGEVkvfxPzsKdgq/shwHaunuCLkjWqeFI9We+XhuKz7XxxRs
z+BAeM0vpZMfBMXwPIRcbiWrsqFUPXq2JSkhc6odR2EMixcnHtuA5ClPU3V54P2X
5o86emXhoB1wqpLvH9a/Uza7vFiW1WyeLCg4rM3kyEVGAsMCKgoMO0oeI1lAqDgY
E/A6nJSxtGhx9fCV4+bIIHUT3B5oAtCKK37G9L6MIQwFbyKt1t2NsqpzFm9AT0rR
7/fUePj4nyKsHWWuiDcNC1cORdRoRC8jYVh4sH+P9RY7YtYO3MU0Zes3wb8OCcBJ
APrhkpdtEJXrMwRb6rvnsFVbbdaAf8LB6gXwgiMipR+YtBYpB4kYlK+3BdWbXNw6
n2E0mBYYnBgAc41lY2R9/TcRo4EYF4DiS5jcM2/QVrFD4xZvEPZ2+9mfLUkY4saf
rVlh6HKXf6yEHmKzMfDhaBOckbhLFrexvhZTipcobk+onO+r7ZF8DwPYz6n3K1gy
3GOiAmGNX1097U9hKnb8qHdUVcdpqDPBfw6TIOEdmUe3XoPpBJVIu4BvG/hqWth0
QzjVSmrTzhAzpYrZgo3RVnud8uUb3DagTkfvQpQPIauM5igIyV6Le8PTR+AsRUxc
ysCENiU28pEUc3smtpmzzXVJM8n4tp04t8YTkcrSZQNDgyClJxfm3diymJtJpxBU
dOFbXTIp7Jb496/fCQZBoI1fdSY95uKmU5JE/Jsp5AtdDf6FnchNLoCBodFevIqN
jGrAngOUoFkLNsm/+YcOWenI6K8hT82KWcGDLex5xdHepU3nL3CJEa4fRk6gJHcQ
ByzHBZc04en9iZb/CL2PPY4ADJsLLYvfuUzO6CaSLFSD5QiZg366tlU3pfY5cm93
9Qo/YC/1wJvnVBA+t1HuuBabAs2u9OQCH0M5VanSjAB0PdKYpVFjkX7jDj0IfPR0

//pragma protect end_data_block
//pragma protect digest_block
7CO4OToooGgXjbb/jJWO5xxZUOs=
//pragma protect end_digest_block
//pragma protect end_protected
